version: '3.8'

services:
  fitsage:
    build: .
    ports:
      - "5002:5002"
    env_file: .env
    volumes:
    - ./FitSage:/app
    develop:
      watch:
      - action: sync
        path: ./ 
        target: /app
        ignore:
          - .git
          - .gitignore
          - .vscode
          - .gitattributes
          - .env
          - .venv
          - .github
      - action: rebuild
        path: ./Dockerfile

  flyway:
    image: flyway/flyway:10.4.1
    env_file: .env
    command: -url=jdbc:mysql://db:3309/masterdb -schemas=masterdb -user=${MYSQL_USER} -password=${MYSQL_ROOT_PASSWORD} -connectRetries=60 migrate
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10m
    volumes:
      - .:/flyway/sql
    depends_on:
      - db

  db:
    build:
      context: ./mysql
    #image: mysql:8.0.35
    command: --default-authentication-plugin=caching_sha2_password
    restart: always
    env_file: .env
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3310:3309"

  adminer:
    image: adminer:4.8.1
    restart: always
    ports:
      - "8081:8080"

volumes:
  mysql_data:
