version: '3.8'

services:
  fitsage:
    build: .
    ports:
      - "5002:5002"
    volumes:
    - .:/app
    develop:
      watch:
      - action: sync
        path: ./ 
        target: /app
        ignore:
          - .git
          - .gitignore
          - .vscode
          - .gitattributes
          - .venv
          - .github
      - action: rebuild
        path: ./Dockerfile
    networks:
      - my-network

  flyway:
    image: flyway/flyway:10.4.1
    env_file: .env
    command: -url=jdbc:mysql://db:3307/masterdb -schemas=masterdb -user=${MYSQL_USER} -password=${MYSQL_PASSWORD} -connectRetries=60 migrate
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10m
    volumes:
      - .:/flyway/sql
    depends_on:
      - db

  db:
    build:
      context: ./mysql
    environment:
      - MYSQL_USER=om
      - MYSQL_ROOT_PASSWORD=El3nksamkfshab3!!!
      - MYSQL_PASSWORD=om4455
      - MYSQL_DATABASE = masterdb
    #image: mysql:8.0.35
    command: --default-authentication-plugin=caching_sha2_password
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - my-network

  adminer:
    image: adminer:4.8.1
    restart: always
    ports:
      - "8081:8081"
    networks:
      - my-network

volumes:
  mysql_data:

networks:
  my-network: