version: '3.8'

services:
  fitsage:
    image: fitsage
    build: .
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m flask run --no-debugger --no-reload --host 0.0.0.0 --port 5003"]
    ports:
      - "5003:5003"
      - "5678:5678"
    environment:
      - FLASK_APP=main.py
    volumes:
      - ./FitSage.:/app

  flyway:
    image: flyway/flyway:10.4.1
    command: -url=jdbc:mysql://db -schemas=user_profiles -user=root -password=${FLYWAY_PASSWORD} -connectRetries=60 migrate
    volumes:
      - .:/flyway/sql
    depends_on:
      - db

  db:
    build: ./mysql
    command: --default-authentication-plugin=caching_sha2_password
    restart: always
    env_file: .env
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      -3306:3306

  adminer:
    image: adminer:4.8.1
    restart: always
    ports:
      - "8081:8080"

volumes:
  mysql_data:
