FROM mysql:8.0.35


ENV MYSQL_USER=om
ENV MYSQL_ROOT_PASSWORD=El3nksamkfshab3!!!
ENV MYSQL_PASSWORD=om4455
ENV MYSQL_DATABASE=masterdb
RUN echo $PATH
RUN microdnf install nano && microdnf clean all

CMD ["mysqld"]

