name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.11.7, 3.12, 3.12.1]  # Python versions to test against

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --timeout=1000 -r requirements.txt  # dont forget requirements.txt file

      - name: Run Python Tests
        run: pytest tests/test_android_build.py

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: path/to/artifact/
